networks:
  dockerapps-net:
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.26
        ipv6_address: 2001:db8:abc2::26
    ports:
      # (Using 9090 because 8080 is taken by qBittorrent)
      - 9090:8080
    environment:
      # Optional: Show stopped containers immediately
      - DOZZLE_FILTER=status=running
    volumes:
      # Critical: Needs access to Docker socket to read logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped